theme = "hugo-paper"
baseURL = "https://jangc.netlify.app/"
languageCode = "ko"
title = "JANGc"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true
disqus_shortname = "jangc94"

[[menu.main]]
  identifier = "Home"
  name = "Home"
  title = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "About"
  name = "about"
  title = "about"
  url = "/About"
  weight =  2


[[menu.main]]
  identifier = "R"
  name = "R"
  title = "R"
  url = "/R"
  weight = 3